
POST http://localhost:3003/user/signup 
Content-Type: application/json

{
    "name" : "Diogo",
    "email" : "diogo@email.com",
    "password" : "123456",
    "cpf" : "11111111111"
}

###
POST http://localhost:3003/user/login 
Content-Type: application/json

{
    "email" : "diogo@email.com",
    "password" : "123456"
}

###
POST http://localhost:3003/payment/create-transaction
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJpZCI6IjY4MDJjNjZjLWZkYjQtNDlhOS04YTY2LTk2YjIyYjg2NTA5YiJ9LCJpYXQiOjE2NzI1NDQxNjIsImV4cCI6MTY3MjU0Nzc2Mn0.9dpOq9SESVbvPzCq3egwKmanY-vN6vBwk6eCEaxigS4

{
    "clientId" : "6802c66c-fdb4-49a9-8a66-96b22b86509b", 
    "method" : "BOLETO", 
    "amount" : 125, 
    "cardHolderName" : "", 
    "cardNumber" : "", 
    "cardExpDate" : "", 
    "cardCvv" : ""
}

###
GET http://localhost:3003/payment/get-payments
