// Endpoint para criar um usuário
POST http://localhost:3003/user/signup 
Content-Type: application/json

{
    "name" : "Diogo",
    "email" : "diogo@email.com",
    "password" : "123456",
    "cpf" : "11111111111"
}

// Endpoint para logar um usuário 
###
POST http://localhost:3003/user/login 
Content-Type: application/json

{
    "email" : "diogo@email.com",
    "password" : "123456"
}

// Endpoint para criar uma transação
###
POST http://localhost:3003/payment/create-transaction
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJpZCI6IjY4MDJjNjZjLWZkYjQtNDlhOS04YTY2LTk2YjIyYjg2NTA5YiJ9LCJpYXQiOjE2NzI2OTI1OTUsImV4cCI6MTY3MjY5NjE5NX0.MDSmQX8dPapdheR6dSHqUwECXbZnTRBCO5jxVc1OdsE

{
    "clientId" : "6802c66c-fdb4-49a9-8a66-96b22b86509b", 
    "method" : "BOLETO", 
    "amount" : 125, 
    "cardHolderName" : "", 
    "cardNumber" : "", 
    "cardExpDate" : "", 
    "cardCvv" : ""
}

// Endpoint para pegar todas transações
###
GET http://localhost:3003/payment/get-payments
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJpZCI6IjY4MDJjNjZjLWZkYjQtNDlhOS04YTY2LTk2YjIyYjg2NTA5YiJ9LCJpYXQiOjE2NzI2OTI1OTUsImV4cCI6MTY3MjY5NjE5NX0.MDSmQX8dPapdheR6dSHqUwECXbZnTRBCO5jxVc1OdsE